enum AgreementActionTypes {
  LOAD_AGREEMENTS = 'LOAD_AGREEMENTS',
  UPDATE_AGREEMENT = 'UPDATE_AGREEMENT',
  UPDATE_AGREEMENT_SUCCESS = 'UPDATE_AGREEMENT_SUCCESS',
  UPDATE_AGREEMENT_ERROR = 'UPDATE_AGREEMENT_ERROR',
  SET_IS_EDITING = 'SET_IS_EDITING',
  SET_AGREEMENT_EXIST = 'SET_AGREEMENT_EXIST',
}

export default AgreementActionTypes;
