enum AgreementActionTypes {
  LOAD_AGREEMENTS = 'LOAD_AGREEMENTS',
  UPDATE_AGREEMENT = 'UPDATE_AGREEMENT',
  UPDATE_AGREEMENT_SUCCESS = 'UPDATE_AGREEMENT_SUCCESS',
  UPDATE_AGREEMENT_ERROR = 'UPDATE_AGREEMENT_ERROR',
}

export default AgreementActionTypes;
