enum WalletActionTypes {
  CONNECTING_WALLET = 'CONNECTING_WALLET',
  SET_CURRENT_WALLET = 'SET_CURRENT_WALLET',
  SET_DISCONECTING = 'SET_DISCONECTING',
  SET_DISCONECTED = 'SET_DISCONECTED',
}

export default WalletActionTypes;
