export enum WalletActionTypes {

	GET_CURRENT_WALLET_LOADING = 'GET_CURRENT_WALLET_LOADING',
	GET_CURRENT_WALLET_SUCCESS = 'GET_CURRENT_WALLET_SUCCESS',
	GET_CURRENT_WALLET_FAILURE = 'GET_CURRENT_WALLET_FAILURE',

	SET_CURRENT_WALLET_LOADING = 'SET_CURRENT_WALLET_LOADING',
	SET_CURRENT_WALLET_SUCCESS = 'SET_CURRENT_WALLET_SUCCESS',
	SET_CURRENT_WALLET_FAILURE = 'SET_CURRENT_WALLET_FAILURE',

	GET_SELECTED_WALLET_LOADING = 'GET_SELECTED_WALLET_LOADING',
	GET_SELECTED_WALLET_SUCCESS = 'GET_SELECTED_WALLET_SUCCESS',
	GET_SELECTED_WALLET_FAILURE = 'GET_SELECTED_WALLET_FAILURE',

	SET_SELECTED_WALLET_LOADING = 'SET_SELECTED_WALLET_LOADING',
	SET_SELECTED_WALLET_SUCCESS = 'SET_SELECTED_WALLET_SUCCESS',
	SET_SELECTED_WALLET_FAILURE = 'SET_SELECTED_WALLET_FAILURE',

	SET_SELECTED_WALLET_TOKEN_LOADING = 'SET_SELECTED_WALLET_TOKEN_LOADING',
	SET_SELECTED_WALLET_TOKEN_SUCCESS = 'SET_SELECTED_WALLET_TOKEN_SUCCESS',
	SET_SELECTED_WALLET_TOKEN_FAILURE = 'SET_SELECTED_WALLET_TOKEN_FAILURE',

	UNLOCK_WALLET_LOADING = 'UNLOCK_WALLET_LOADING',
	UNLOCK_WALLET_SUCCESS = 'UNLOCK_WALLET_SUCCESS',
	UNLOCK_WALLET_FAILURE = 'UNLOCK_WALLET_FAILURE',

	CONNECT_WALLET_LOADING = 'UNLOCK_WALLET_LOADING',
	CONNECT_WALLET_SUCCESS = 'UNLOCK_WALLET_SUCCESS',
	CONNECT_WALLET_FAILURE = 'UNLOCK_WALLET_FAILURE',

	DISCONNECT_WALLET_LOADING = 'UNLOCK_WALLET_LOADING',
	DISCONNECT_WALLET_SUCCESS = 'UNLOCK_WALLET_SUCCESS',
	DISCONNECT_WALLET_FAILURE = 'UNLOCK_WALLET_FAILURE',
	SHOW_MY_CURRENT_WALLET = 'SHOW_MY_CURRENT_WALLET'
}
