module.exports = {
  VERSION: "1.0.0",
  DAITokenContract: {
    raw: {
      abi: [
        {
          inputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "constructor",
          signature: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "src",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "guy",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "wad",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
          signature:
            "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
        },
        {
          anonymous: true,
          inputs: [
            {
              indexed: true,
              internalType: "bytes4",
              name: "sig",
              type: "bytes4",
            },
            {
              indexed: true,
              internalType: "address",
              name: "usr",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "arg1",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "arg2",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "LogNote",
          type: "event",
          signature:
            "0xd3d8bec38a91a5f4411247483bc030a174e77cda9c0351924c759f41453aa5e8",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "src",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "dst",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "wad",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
          signature:
            "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
        },
        {
          constant: true,
          inputs: [],
          name: "DOMAIN_SEPARATOR",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x3644e515",
        },
        {
          constant: true,
          inputs: [],
          name: "PERMIT_TYPEHASH",
          outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x30adf81f",
        },
        {
          constant: true,
          inputs: [
            { internalType: "address", name: "", type: "address" },
            { internalType: "address", name: "", type: "address" },
          ],
          name: "allowance",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0xdd62ed3e",
        },
        {
          constant: true,
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "balanceOf",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x70a08231",
        },
        {
          constant: true,
          inputs: [],
          name: "chainId_",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0xe17a778a",
        },
        {
          constant: true,
          inputs: [],
          name: "decimals",
          outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x313ce567",
        },
        {
          constant: true,
          inputs: [],
          name: "name",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x06fdde03",
        },
        {
          constant: true,
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "nonces",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x7ecebe00",
        },
        {
          constant: true,
          inputs: [],
          name: "symbol",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x95d89b41",
        },
        {
          constant: true,
          inputs: [],
          name: "totalSupply",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x18160ddd",
        },
        {
          constant: true,
          inputs: [],
          name: "version",
          outputs: [{ internalType: "string", name: "", type: "string" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0x54fd4d50",
        },
        {
          constant: true,
          inputs: [{ internalType: "address", name: "", type: "address" }],
          name: "wards",
          outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
          payable: false,
          stateMutability: "view",
          type: "function",
          signature: "0xbf353dbb",
        },
        {
          constant: false,
          inputs: [{ internalType: "address", name: "guy", type: "address" }],
          name: "rely",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x65fae35e",
        },
        {
          constant: false,
          inputs: [{ internalType: "address", name: "guy", type: "address" }],
          name: "deny",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x9c52a7f1",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "dst", type: "address" },
            { internalType: "uint256", name: "wad", type: "uint256" },
          ],
          name: "transfer",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0xa9059cbb",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "src", type: "address" },
            { internalType: "address", name: "dst", type: "address" },
            { internalType: "uint256", name: "wad", type: "uint256" },
          ],
          name: "transferFrom",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x23b872dd",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "usr", type: "address" },
            { internalType: "uint256", name: "wad", type: "uint256" },
          ],
          name: "mint",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x40c10f19",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "usr", type: "address" },
            { internalType: "uint256", name: "wad", type: "uint256" },
          ],
          name: "burn",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x9dc29fac",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "usr", type: "address" },
            { internalType: "uint256", name: "wad", type: "uint256" },
          ],
          name: "approve",
          outputs: [{ internalType: "bool", name: "", type: "bool" }],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x095ea7b3",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "usr", type: "address" },
            { internalType: "uint256", name: "wad", type: "uint256" },
          ],
          name: "push",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0xb753a98c",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "usr", type: "address" },
            { internalType: "uint256", name: "wad", type: "uint256" },
          ],
          name: "pull",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0xf2d5d56b",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "src", type: "address" },
            { internalType: "address", name: "dst", type: "address" },
            { internalType: "uint256", name: "wad", type: "uint256" },
          ],
          name: "move",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0xbb35783b",
        },
        {
          constant: false,
          inputs: [
            { internalType: "address", name: "holder", type: "address" },
            { internalType: "address", name: "spender", type: "address" },
            { internalType: "uint256", name: "nonce", type: "uint256" },
            { internalType: "uint256", name: "expiry", type: "uint256" },
            { internalType: "bool", name: "allowed", type: "bool" },
            { internalType: "uint8", name: "v", type: "uint8" },
            { internalType: "bytes32", name: "r", type: "bytes32" },
            { internalType: "bytes32", name: "s", type: "bytes32" },
          ],
          name: "permit",
          outputs: [],
          payable: false,
          stateMutability: "nonpayable",
          type: "function",
          signature: "0x8fcbaf0c",
        },
      ],
    },
    address: {
      "rinkeby-fork": "0x356Eed05d8CAF4544E2cfBBB91923d411228BF95",
      rinkeby: "0x356Eed05d8CAF4544E2cfBBB91923d411228BF95",
      testnet: "ec5dcb5dbf4b114c9d0f65bccab49ec54f6a0867",
    },
  },
};
