export enum AuthActionTypes {
    LOGIN_LOADING = 'LOGIN_LOADING',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    SIGN_UP_LOADING = 'SIGN_UP_LOADING',
    SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE = 'SIGN_UP_FAILURE',
    LOGOUT_LOADING = 'LOGOUT_LOADING',
    LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE = 'LOGOUT_FAILURE'
}
