export enum DocumentsActionTypes {
    GET_DOCUMENTS_LOADING = 'GET_DOCUMENTS_LOADING',
    GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS',
    GET_DOCUMENTS_FAILURE = 'GET_DOCUMENTS_FAILURE',

    GET_SELECTED_DOCUMENT_SUCCESS = 'GET_SELECTED_DOCUMENT_SUCCESS',
}
