export enum DocumentsActionTypes {
	GET_DOCUMENTS_LOADING = 'GET_DOCUMENTS_LOADING',
	GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS',
	GET_DOCUMENTS_FAILURE = 'GET_DOCUMENTS_FAILURE',
	UPLOAD_DOCUMENTS_LOADING = 'UPLOAD_DOCUMENTS_LOADING',
	UPLOAD_DOCUMENTS_SUCCESS = 'UPLOAD_DOCUMENTS_SUCCESS',
	UPLOAD_DOCUMENTS_FAILURE = 'UPLOAD_DOCUMENTS_FAILURE',
	GET_SELECTED_DOCUMENT_LOADING = 'GET_SELECTED_DOCUMENT_LOADING',
	GET_SELECTED_DOCUMENT_SUCCESS = 'GET_SELECTED_DOCUMENT_SUCCESS',
	CREATE_AGREEMENT_LOADING = 'CREATE_AGREEMENT_LOADING',
	CREATE_AGREEMENT_SUCCESS = 'CREATE_AGREEMENT_SUCCESS',
	CREATE_AGREEMENT_FAILURE = 'CREATE_AGREEMENT_FAILURE',
	SET_AGREEMENT_FORM_INFO = 'SET_AGREEMENT_FORM_INFO'
}
