export enum SmartAgreementsTypes {
    SET_NDA_AGREEMENT_DATA = 'SET_NDA_AGREEMENT_DATA',
    SET_ADVISOR_AGREEMENT_DATA = 'SET_ADVISOR_AGREEMENT_DATA',
    SET_CIIA_AGREEMENT_DATA = 'SET_CIIA_AGREEMENT_DATA',
    SET_REFERRAL_AGEEMENT_DATA = 'SET_REFERRAL_AGEEMENT_DATA',
    SET_SAFT_AGEEMENT_DATA = 'SET_SAFT_AGEEMENT_DATA'
}