export enum WalletActionTypes {
	GENERATE_PHRASE = 'GENERATE_PHRASE',
	ADD_WORD = 'ADD_WORD',
	REMOVE_WORD = 'REMOVE_WORD',
	GET_WALLETS_LOADING = 'GET_WALLETS_LOADING',
	GET_WALLETS_SUCCESS = 'GET_WALLETS_SUCCESS',
	GET_WALLETS_FAILURE = 'GET_WALLETS_FAILURE',
	CREATE_WALLET_LOADING = 'CREATE_WALLET_LOADING',
	CREATE_WALLET_SUCCESS = 'CREATE_WALLET_SUCCESS',
	CREATE_WALLET_FAILURE = 'CREATE_WALLET_FAILURE',
	IMPORT_WALLET_LOADING = 'IMPORT_WALLET_LOADING',
	IMPORT_WALLET_SUCCESS = 'IMPORT_WALLET_SUCCESS',
	IMPORT_WALLET_FAILURE = 'IMPORT_WALLET_FAILURE',
	EXPORT_WALLET_LOADING = 'EXPORT_WALLET_LOADING',
	EXPORT_WALLET_SUCCESS = 'EXPORT_WALLET_SUCCESS',
	EXPORT_WALLET_FAILURE = 'EXPORT_WALLET_FAILURE',

	GET_CURRENT_WALLET_LOADING = 'GET_CURRENT_WALLET_LOADING',
	GET_CURRENT_WALLET_SUCCESS = 'GET_CURRENT_WALLET_SUCCESS',
	GET_CURRENT_WALLET_FAILURE = 'GET_CURRENT_WALLET_FAILURE',

	SET_CURRENT_WALLET_LOADING = 'SET_CURRENT_WALLET_LOADING',
	SET_CURRENT_WALLET_SUCCESS = 'SET_CURRENT_WALLET_SUCCESS',
	SET_CURRENT_WALLET_FAILURE = 'SET_CURRENT_WALLET_FAILURE'
}
